server:
  port: 8090
spring:
  profiles:
    include: secret
  mail:
    host: smtp.gmail.com
    port: 587
    username: alsdudrb123@gmail.com
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/motivation?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: qkqh134679258
  security:
    user:
      name: user
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  site:
    name: 모티베이션
    baseUrl: "http://localhost:8090"
  genFile:
    dirPath: c:/temp/demo5